import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { CustomThemeProvider } from "@/styles/Themes/CustomThemeProvider/provider";
import { GlobalStyles } from "./global";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Space Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="pt-br">
      <CustomThemeProvider>
        <body className={inter.className}>
          {children}
          
        </body>

      <GlobalStyles />
      </CustomThemeProvider>
    </html>
  );
}
